
filenames = ["AGUIndexTerms.csv",
    "Astrophysics and Cosmic Engine Glossary.csv",
    "Beyond Earth_ A Chronicle of Deep Space Exploration, 1958 - 2016_ e-book.csv",
    "Biology Glossary.csv",
    "ESA Space Weather Glossary.csv",
    "Gazetteer of Planetary Nomenclature Feature Terms.csv",
    "Gazetteer of Planetary Nomenclature Planetary Names.csv",
    "Global Change Master Directory (GCMD).csv",
    "IEEE Thesaurus and Taxonomy.csv",
    "ISO 21348.csv",
    "lunarinstrumentlist.csv",
    "NASA CCMC.csv",
    "NASA Heliophysics Vocabulary.csv",
    "NASA Thesaurus.csv",
    "Planetary Science Research Discoveries Glossary.csv",
    "SMD Glossary.csv",
    "Space Weather Glossary.csv",
    "SPASE Dictionary.csv"]

dict_input = {"AGUIndexTerms.csv":"",
    "Astrophysics and Cosmic Engine Glossary.csv":"https://www.atnf.csiro.au/outreach/education/senior/astrophysics/astrophysics_glossary.html#A-spectral-class",
    "Beyond Earth_ A Chronicle of Deep Space Exploration, 1958 - 2016_ e-book.csv":"https://www.nasa.gov/sites/default/files/atoms/files/beyond-earth-tagged.pdf",
    "Biology Glossary.csv":"https://www.boyertownasd.org/site/handlers/filedownload.ashx?moduleinstanceid=4502&dataid=8141&FileName=NEW%20GLOSSARY%20COMBINED.pdf",
    "ESA Space Weather Glossary.csv":"https://swe.ssa.esa.int/glossary",
    "Gazetteer of Planetary Nomenclature Feature Terms.csv":"https://planetarynames.wr.usgs.gov/DescriptorTerms",
    "Gazetteer of Planetary Nomenclature Planetary Names.csv":"https://planetarynames.wr.usgs.gov/Page/Planets",
    "Global Change Master Directory (GCMD).csv":["https://gcmd.earthdata.nasa.gov/static/kms/",
                    "https://earthdata.nasa.gov/earth-observation-data/find-data/idn/gcmd-keywords"],
    "IEEE Thesaurus and Taxonomy.csv":"https://caralsiseco.jimdofree.com/app/download/10208814770/S3.2.+ieee-thesaurus.pdf",
    "ISO 21348.csv":"https://spacewx.net/wp-content/uploads/2020/08/ISO_PRF_21348_e_review.pdf",
    "lunarinstrumentlist.csv":"",
    "NASA CCMC.csv":"https://ccmc.gsfc.nasa.gov/RoR_WWW/presentations/Glossary_of_Space_Weather_terms.pdf",
    "NASA Heliophysics Vocabulary.csv":"https://www.nasa.gov/mission_pages/sunearth/spaceweather/vocabulary.html",
    "NASA Thesaurus.csv":"https://www.sti.nasa.gov/nasa-thesaurus/",
    "Planetary Science Research Discoveries Glossary.csv":"http://www.psrd.hawaii.edu/PSRDglossary.html",
    "SMD Glossary.csv":"https://science.nasa.gov/glossary",
    "Space Weather Glossary.csv":["https://www.swpc.noaa.gov/content/space-weather-glossary",
                    "https://spacewx.com/glossary/"],
    "SPASE Dictionary.csv":"https://spase-group.org/data/model/search/index.html?version=2.4.0"}

dict_input_extracted = {"AGUIndexTerms.csv":"",
    "Astrophysics and Cosmic Engine Glossary.csv":"astrophysics_glossary.html#A-spectral-class.csv",
    "Beyond Earth_ A Chronicle of Deep Space Exploration, 1958 - 2016_ e-book.csv":"beyond-earth-tagged.pdf.csv",
    "Biology Glossary.csv":"filedownload.ashx?moduleinstanceid=4502&dataid=8141&FileName=NEW%20GLOSSARY%20COMBINED.pdf.csv",
    "ESA Space Weather Glossary.csv":"swe.ssa.esa.int_glossary.csv",
    "Gazetteer of Planetary Nomenclature Feature Terms.csv":"DescriptorTerms.csv",
    "Gazetteer of Planetary Nomenclature Planetary Names.csv":"Planets.csv",
    "Global Change Master Directory (GCMD).csv":["kms.csv",
                    "gcmd-keywords.csv"],
    "IEEE Thesaurus and Taxonomy.csv":"S3.2.+ieee-thesaurus.pdf.csv",
    "ISO 21348.csv":"ISO_PRF_21348_e_review.pdf.csv",
    "lunarinstrumentlist.csv":"",
    "NASA CCMC.csv":"Glossary_of_Space_Weather_terms.pdf.csv",
    "NASA Heliophysics Vocabulary.csv":"vocabulary.html.csv",
    "NASA Thesaurus.csv":"nasa-thesaurus.csv",
    "Planetary Science Research Discoveries Glossary.csv":"PSRDglossary.html.csv",
    "SMD Glossary.csv":"science.nasa.gov_glossary.csv",
    "Space Weather Glossary.csv":["space-weather-glossary.csv",
                    "spacewx.com_glossary.csv"],
    "SPASE Dictionary.csv":"index.html?version=2.4.0.csv"}


dict_input_json={
    "AMS Glossary of Meteorology.json":"https://glossary.ametsoc.org/wiki/Welcome",
    "AMS Journal Keywords.json":"https://www.ametsoc.org/ams/index.cfm?LinkServID=59DF8BDA-B15A-A626-8E303F747D5D3452",
    "ANZSRC Fields of Research Classification.json":"https://vocabs.ardc.edu.au/viewById/316",
    "Astrobiology Resource Metadata Standard (ARMS) Keywords.json":"https://ahed.nasa.gov/help/help-keywords",
    "Astrogeology Science Center Glossary.json":"https://www.usgs.gov/centers/astrogeology-science-center/glossary-terms",
    "Astronomical Subject Keywords.json":"https://journals.aas.org/keywords-2013/",
    "Astrophysics and Cosmic Engine Glossary.json":"https://www.atnf.csiro.au/outreach/education/senior/astrophysics/astrophysics_glossary.html#A-spectral-class",
    "Beyond Earth.json":"https://www.nasa.gov/sites/default/files/atoms/files/beyond-earth-tagged.pdf",
    "Biology Dictionary.json":"https://www.biologyonline.com/dictionary",
    "Biology Glossary.json":"https://www.boyertownasd.org/site/handlers/filedownload.ashx?moduleinstanceid=4502&dataid=8141&FileName=NEW%20GLOSSARY%20COMBINED.pdf",
    "Canadian Space Agency Astronautics Vocabulary.json":"https://www.asc-csa.gc.ca/eng/resources/vocabulary/default.asp",
    "Dictionary of Techincal Terms for Aerospace Use.json":"https://er.jsc.nasa.gov/seh/menu.html",
    "ESA Space Weather Glossary.json":"https://swe.ssa.esa.int/glossary",
    "Gazetteer of Planetary Nomenclature Feature Terms.json":"https://planetarynames.wr.usgs.gov/DescriptorTerms",
    "Gazetteer of Planetary Nomenclature Planetary Names.json":"https://planetarynames.wr.usgs.gov/Page/Planets",
    "Gazetteer of Planetary Nomenclature Ring and Ring Gaps.json":"https://planetarynames.wr.usgs.gov/Page/Rings",
    "Gazetteer of Planetary Nomenclature.json":"https://planetarynames.wr.usgs.gov/AdvancedSearch",
    "Global Change Master Directory (GCMD).json":["https://gcmd.earthdata.nasa.gov/static/kms/",
                    "https://earthdata.nasa.gov/earth-observation-data/find-data/idn/gcmd-keywords"],
    "Heliophysics Events Knowledgebase.json":"https://www.lmsal.com/hek/VOEvent_Spec.html",
    "IEEE Thesaurus and Taxonomy.json":"https://caralsiseco.jimdofree.com/app/download/10208814770/S3.2.+ieee-thesaurus.pdf",
    "Integrated Taxonomic Information System.json":"https://www.itis.gov/",
    "ISO 21348.json":"https://spacewx.net/wp-content/uploads/2020/08/ISO_PRF_21348_e_review.pdf",
    "IVOA Vocabulary.json":"https://www.ivoa.net/rdf/uat/2021-02-11/uat.html",
    "Lunar Instrument List.json":"https://www.lpi.usra.edu/lunar/instruments/",
    "NASA CCMC.csv":"https://ccmc.gsfc.nasa.gov/RoR_WWW/presentations/Glossary_of_Space_Weather_terms.pdf",
    "NASA Heliophysics Vocabulary.json":"https://www.nasa.gov/mission_pages/sunearth/spaceweather/vocabulary.html",
    "NASA Thesaurus.json":"https://www.sti.nasa.gov/nasa-thesaurus/",
    "Planetary Science Research Discoveries Glossary.json":"http://www.psrd.hawaii.edu/PSRDglossary.html",
    "SMD Glossary.json":"https://science.nasa.gov/glossary",
    "Solar System Glossary.json":"https://solarsystem.nasa.gov/basics/glossary/",
    "Space Weather Glossary (Second).json":"https://spacewx.com/glossary/",
    "Space Weather Glossary.json":"https://www.swpc.noaa.gov/content/space-weather-glossary",
    "SPASE Dictionary.json":"https://spase-group.org/data/model/search/index.html?version=2.4.0",
    "Unified Astronomy Thesaurus (UAT).json":"https://astrothesaurus.org/",
    "Unified Content Descriptor.json":"http://cdsweb.u-strasbg.fr/UCD/ucd1p-words.txt",
    "University of Maryland Ontologies.json":"https://www.astro.umd.edu/~eshaya/astro-onto/ontologies",
    "USGS Thesaurus.json":"https://apps.usgs.gov/thesaurus/"
} 

dict_input_extracted_json = {
    "AMS Glossary of Meteorology.json":"Welcome.csv",
    "AMS Journal Keywords.json":"",
    "ANZSRC Fields of Research Classification.json":"316.csv",
    "Astrobiology Resource Metadata Standard (ARMS) Keywords.json":"help-keywords.csv",
    "Astrogeology Science Center Glossary.json":"glossary-terms.csv",
    "Astronomical Subject Keywords.json":"keywords-2013.csv",
    "Astrophysics and Cosmic Engine Glossary.json":"astrophysics_glossary.html#A-spectral-class.csv",
    "Beyond Earth.json":"beyond-earth-tagged.pdf.csv",
    "Biology Dictionary.json":"dictionary.csv",
    "Biology Glossary.json":"filedownload.ashx?moduleinstanceid=4502&dataid=8141&FileName=NEW%20GLOSSARY%20COMBINED.pdf.csv",
    "Canadian Space Agency Astronautics Vocabulary.json":"default.asp.csv",
    "Dictionary of Techincal Terms for Aerospace Use.json":"menu.html.csv",
    "ESA Space Weather Glossary.json":"swe.ssa.esa.int_glossary.csv",
    "Gazetteer of Planetary Nomenclature Feature Terms.json":"DescriptorTerms.csv",
    "Gazetteer of Planetary Nomenclature Planetary Names.json":"Planets.csv",
    "Gazetteer of Planetary Nomenclature Ring and Ring Gaps.json":"Rings.csv",
    "Gazetteer of Planetary Nomenclature.json":"AdvancedSearch.csv",
    "Global Change Master Directory (GCMD).json":["kms.csv",
                    "gcmd-keywords.csv"],
    "Heliophysics Events Knowledgebase.json":"VOEvent_Spec.html.csv",
    "IEEE Thesaurus and Taxonomy.json":"S3.2.+ieee-thesaurus.pdf.csv",
    "Integrated Taxonomic Information System.json":"www.itis.gov.csv",
    "ISO 21348.json":"ISO_PRF_21348_e_review.pdf.csv",
    "IVOA Vocabulary.json":"uat.html.csv",
    "Lunar Instrument List.json":"instruments.csv",
    "NASA CCMC.csv":"Glossary_of_Space_Weather_terms.pdf.csv",
    "NASA Heliophysics Vocabulary.json":"vocabulary.html.csv",
    "NASA Thesaurus.json":"nasa-thesaurus.csv",
    "Planetary Science Research Discoveries Glossary.json":"PSRDglossary.html.csv",
    "SMD Glossary.json":"science.nasa.gov_glossary.csv",
    "Solar System Glossary.json":"glossary.csv",
    "Space Weather Glossary (Second).json":"space-weather-glossary.csv",
    "Space Weather Glossary.json":"spacewx.com_glossary.csv",
    "SPASE Dictionary.json":"index.html?version=2.4.0.csv",
    "Unified Astronomy Thesaurus (UAT).json":"astrothesaurus.org.csv",
    "Unified Content Descriptor.json":"ucd1p-words.txt.csv",
    "University of Maryland Ontologies.json":"ontologies.csv",
    "USGS Thesaurus.json":"thesaurus.csv"
    }

